// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4e-poLQOeVYcvICnIsT5q5-ZkMDsnmk8',
    appId: '1:474124485639:web:c89a344c83babaa6dcd6a2',
    messagingSenderId: '474124485639',
    projectId: 'sessentials-58072',
    authDomain: 'sessentials-58072.firebaseapp.com',
    storageBucket: 'sessentials-58072.firebasestorage.app',
    measurementId: 'G-36CY1SDFJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz9w2c43QY1d4K3tvedhwTvP4_E_z7KaU',
    appId: '1:474124485639:android:7caab8796c41531edcd6a2',
    messagingSenderId: '474124485639',
    projectId: 'sessentials-58072',
    storageBucket: 'sessentials-58072.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLMM2CHI71UrokytLpoBGQctbthMlrqdM',
    appId: '1:474124485639:ios:ae67342f774f3c9bdcd6a2',
    messagingSenderId: '474124485639',
    projectId: 'sessentials-58072',
    storageBucket: 'sessentials-58072.firebasestorage.app',
    iosBundleId: 'com.example.flutterEcomorece',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLMM2CHI71UrokytLpoBGQctbthMlrqdM',
    appId: '1:474124485639:ios:976a259a5fb1b17cdcd6a2',
    messagingSenderId: '474124485639',
    projectId: 'sessentials-58072',
    storageBucket: 'sessentials-58072.firebasestorage.app',
    iosBundleId: 'com.example.flutter4sessentials',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4e-poLQOeVYcvICnIsT5q5-ZkMDsnmk8',
    appId: '1:474124485639:web:dd49b1b2e1c3970ddcd6a2',
    messagingSenderId: '474124485639',
    projectId: 'sessentials-58072',
    authDomain: 'sessentials-58072.firebaseapp.com',
    storageBucket: 'sessentials-58072.firebasestorage.app',
    measurementId: 'G-X0XVZ2C2WJ',
  );
}
